import Link from "next/link";
import { linkDiscordAccount, linkPatreonAccount } from "@/app/account/actions";
import type { WebsiteOnboardingSummary } from "@/app/lib/hosting/membership-onboarding";
const messages: Record<WebsiteOnboardingSummary["status"], string> = {
    signed_out: "Sign in or create an account to set up a server.", needs_discord: "Connect Discord to this same website account before server setup.", identity_repair: "Your account identities need repair. Do not create or merge a second account; contact support.", configuration_blocked: "Membership server setup is not configured yet. Contact support. Existing servers and independent grants are unaffected.", needs_patreon: "Connect Patreon to check your subscription benefits for this account.", verification_pending: "Verification is awaiting your account confirmation. Return to your account; do not launch another authorization.", sync_pending: "Membership was checked; allocation synchronization is pending. Refresh status.", nonqualifying: "No qualifying subscription benefit was verified. Subscribe or upgrade on Patreon, then Check again.", verification_expired: "Check your membership again through Patreon authorization. Verification lasts at most 24 hours for new allocation only.", review_required: "Membership or allocation needs review. Contact support; existing servers remain available.", unavailable: "Account or membership status could not be confirmed. Retry status; Check again uses a new Patreon authorization.", eligible: "Your allocation is available.", quota_exhausted: "Your server allowance is in use. Manage your owned servers below.", provisioning_unavailable: "Provisioning is temporarily unavailable. Refresh status later.", created: "Your server was assigned. Manage it below.",
};
export function MembershipNextStep({ summary }: { summary: WebsiteOnboardingSummary }) {
    return <section className="mt-7 border border-gold/30 bg-surface p-5" aria-label="Account setup next step">
        <p role="status">{messages[summary.status]}</p>
        {summary.nextAction === "confirm_account" && <Link className="mt-3 block underline" href="/account">Return to account confirmation</Link>}
        {summary.nextAction === "sign_in" && <Link href="/login?next=/servers">Sign in / create account</Link>}
        {summary.nextAction === "connect_discord" && <form action={linkDiscordAccount}><input type="hidden" name="returnPath" value="/servers" /><p className="mt-3 text-sm">Confirm that you want to link Discord to your currently signed-in account. Separate existing accounts require support; no email merge is performed.</p><button className="mt-3 underline" type="submit">Confirm and connect Discord</button></form>}
        {["connect_patreon", "check_again", "subscribe_or_upgrade"].includes(summary.nextAction) && <form action={linkPatreonAccount}><input type="hidden" name="returnPath" value="/servers" /><button className="mt-3 underline" type="submit">{summary.nextAction === "connect_patreon" ? "Connect Patreon" : "Check again with Patreon"}</button></form>}
        {summary.nextAction === "subscribe_or_upgrade" && <a href="https://www.patreon.com/" className="mt-3 block underline" rel="noreferrer">Open Patreon</a>}
        {["repair_account", "contact_support"].includes(summary.nextAction) && <Link className="mt-3 block underline" href="/account">Account status and repair guidance</Link>}
        <p className="mt-3 text-sm text-foreground-muted">Existing server management, Start/Stop and saves do not depend on membership refresh. No automatic stop or deletion is started by expired membership evidence.</p>
    </section>;
}
