begin;

-- Delivery is receipt/lease driven. A sequence remains a stable scheduling hint,
-- but no consumer may exclude an unacknowledged row merely because it has seen a
-- larger sequence. This removes the need to serialize unrelated membership
-- transactions to sequence allocation/commit order.
alter table public.membership_outbox
    add column claim_id uuid,
    add column claim_expires_at timestamptz,
    add constraint membership_outbox_claim_pair check (
        (claim_id is null) = (claim_expires_at is null)
    ),
    add constraint membership_outbox_ack_releases_claim check (
        receipt_id is null or (claim_id is null and claim_expires_at is null)
    );

-- Retain the private helper for rolling compatibility with already-deployed
-- functions. It no longer acquires the subsystem-wide advisory lock. The
-- account, Auth, Patreon and worker/singleton fences remain independently
-- bounded in their owning functions.
create or replace function public.membership_lock() returns void
language plpgsql set search_path = '' as $function$
begin
    return;
end;
$function$;
comment on function public.membership_lock() is
    'Rolling-compatibility no-op. Receipt-driven delivery replaced the global membership commit-order lock.';

-- Version-one rollback clients remain safe: p_cursor is only a scheduling token.
-- Every page starts from the oldest unacknowledged event, so a late commit can
-- never be hidden behind an already-observed sequence.
create or replace function public.membership_changes(p_cursor text,p_limit integer) returns jsonb
language plpgsql security definer set search_path = '' as $function$
declare result jsonb;
begin
    perform set_config('lock_timeout',public.membership_lock_budget(),true);
    if p_limit is null or p_limit not between 1 and 50
        or (p_cursor is not null and p_cursor !~ '^(0|[1-9][0-9]{0,19})$') then
        raise exception 'Invalid page';
    end if;
    select jsonb_build_object(
        'version',1,
        'cursor',case when count(*) = 0 then p_cursor else greatest(
            coalesce(max(sequence)::numeric,0),coalesce(p_cursor::numeric,0)+1
        )::text end,
        'events',coalesce(jsonb_agg(jsonb_build_object(
            'eventId',event_id,'accountId',account_id
        ) order by sequence),'[]'::jsonb)
    ) into result
    from (
        select sequence,event_id,account_id
        from public.membership_outbox
        where receipt_id is null and (
            claim_id is null or claim_expires_at <= clock_timestamp()
        )
        order by sequence
        limit p_limit
    ) page;
    return result;
end;
$function$;

-- The version-one acknowledgement remains available for a bounded rollback.
-- It cannot steal a live version-two claim, and it releases any expired claim
-- while preserving the original idempotent receipt contract.
create or replace function public.membership_ack(
    p_event_id uuid,p_receipt_id uuid
) returns jsonb
language plpgsql security definer set search_path = '' as $function$
declare outbox public.membership_outbox; account uuid;
begin
    perform set_config('lock_timeout',public.membership_lock_budget(),true);
    select account_id into account from public.membership_outbox where event_id=p_event_id;
    if not found then raise exception 'Receipt conflict'; end if;
    if not pg_try_advisory_xact_lock(hashtextextended(account::text,702)) then
        return jsonb_build_object('version',1,'retry',true);
    end if;
    select * into outbox from public.membership_outbox
        where event_id=p_event_id for update;
    if not found then raise exception 'Receipt conflict'; end if;
    if outbox.receipt_id is not null then
        if outbox.receipt_id<>p_receipt_id then raise exception 'Receipt conflict'; end if;
        return jsonb_build_object('version',1,'acknowledged',true,
            'eventId',p_event_id,'receiptId',p_receipt_id);
    end if;
    if outbox.claim_id is not null and outbox.claim_expires_at>clock_timestamp() then
        return jsonb_build_object('version',1,'retry',true);
    end if;
    update public.membership_outbox set receipt_id=p_receipt_id,
        acknowledged_at=clock_timestamp(),claim_id=null,claim_expires_at=null
        where event_id=p_event_id;
    perform public.membership_notify(outbox.account_id,true);
    return jsonb_build_object('version',1,'acknowledged',true,
        'eventId',p_event_id,'receiptId',p_receipt_id);
end;
$function$;

-- A claim token is generated by the consumer before the HTTP request. Replaying
-- the same request after response loss returns the same still-unacknowledged
-- rows and the original bounded lease. Expired claims are recoverable after a
-- consumer crash; SKIP LOCKED bounds concurrent claimers without an exception.
create function public.membership_claim(p_claim_id uuid,p_limit integer) returns jsonb
language plpgsql security definer set search_path = '' as $function$
declare
    claimed_at timestamptz := clock_timestamp();
    expires_at timestamptz;
    replay boolean;
    result jsonb;
begin
    perform set_config('lock_timeout',public.membership_lock_budget(),true);
    if p_claim_id is null or p_limit is null or p_limit not between 1 and 50 then
        raise exception 'Invalid claim';
    end if;
    if not pg_try_advisory_xact_lock(hashtextextended(p_claim_id::text,703)) then
        return jsonb_build_object('version',2,'retry',true);
    end if;
    select exists(select 1 from public.membership_outbox
        where receipt_id is null and claim_id=p_claim_id) into replay;
    if replay then
        select min(claim_expires_at) into expires_at
            from public.membership_outbox where receipt_id is null and claim_id=p_claim_id;
    else
        expires_at := claimed_at + interval '45 seconds';
    end if;
    with candidates as materialized (
        select sequence
        from public.membership_outbox
        where receipt_id is null and case when replay then claim_id=p_claim_id
            else claim_id is null or claim_expires_at <= claimed_at end
        order by sequence
        for update skip locked
        limit p_limit
    ), claimed as (
        update public.membership_outbox outbox
        set claim_id=p_claim_id,claim_expires_at=expires_at
        from candidates
        where outbox.sequence=candidates.sequence
        returning outbox.sequence,outbox.event_id,outbox.account_id
    )
    select jsonb_build_object(
        'version',2,
        'claimId',p_claim_id,
        'leaseExpiresAt',to_char(expires_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
        'events',coalesce(jsonb_agg(jsonb_build_object(
            'eventId',event_id,'accountId',account_id
        ) order by sequence),'[]'::jsonb)
    ) into result from claimed;
    return result;
end;
$function$;

create function public.membership_ack_claim(
    p_event_id uuid,p_receipt_id uuid,p_claim_id uuid
) returns jsonb
language plpgsql security definer set search_path = '' as $function$
declare
    outbox public.membership_outbox;
    account uuid;
begin
    perform set_config('lock_timeout',public.membership_lock_budget(),true);
    if p_event_id is null or p_receipt_id is null or p_claim_id is null then
        raise exception 'Invalid acknowledgement';
    end if;
    select account_id into account from public.membership_outbox where event_id=p_event_id;
    if not found then raise exception 'Receipt conflict'; end if;
    if not pg_try_advisory_xact_lock(hashtextextended(account::text,702)) then
        return jsonb_build_object('version',2,'retry',true);
    end if;
    select * into outbox from public.membership_outbox
        where event_id=p_event_id for update;
    if not found then raise exception 'Receipt conflict'; end if;
    if outbox.receipt_id is not null then
        if outbox.receipt_id<>p_receipt_id then raise exception 'Receipt conflict'; end if;
        return jsonb_build_object('version',2,'acknowledged',true,
            'eventId',p_event_id,'receiptId',p_receipt_id,'claimId',p_claim_id);
    end if;
    if outbox.claim_id is distinct from p_claim_id
        or outbox.claim_expires_at <= clock_timestamp() then
        return jsonb_build_object('version',2,'retry',true);
    end if;
    update public.membership_outbox set receipt_id=p_receipt_id,
        acknowledged_at=clock_timestamp(),claim_id=null,claim_expires_at=null
        where event_id=p_event_id;
    -- An old acknowledgement still repairs delivery for the newest account head.
    perform public.membership_notify(outbox.account_id,true);
    return jsonb_build_object('version',2,'acknowledged',true,
        'eventId',p_event_id,'receiptId',p_receipt_id,'claimId',p_claim_id);
end;
$function$;

-- Browser status is a read path when the current Auth projection already agrees
-- with the durable head. Only a detected identity/link drift enters the account
-- mutation fence. A normal account-lock race is protocol backpressure, not a
-- PostgreSQL ERROR, and is retried at the Edge seam.
create or replace function public.membership_status(
    p_account_id uuid,p_discord_user_id text
) returns jsonb
language plpgsql security definer set search_path = '' as $function$
declare
    h public.membership_heads;
    current_patreon text;
    snapshot jsonb;
    pending boolean;
begin
    perform set_config('lock_timeout',public.membership_lock_budget(),true);
    select * into h from public.membership_heads where account_id=p_account_id;
    select patreon_user_id into current_patreon
        from public.patreon_accounts where user_id=p_account_id;
    if h.account_id is not null and h.link_state<>'account_deleted'
        and h.discord_user_id is not distinct from p_discord_user_id
        and h.patreon_user_id is not distinct from current_patreon
        and (current_patreon is not null or h.link_state='unlinked') then
        snapshot := public.membership_snapshot_json(h);
    else
        if not pg_try_advisory_xact_lock(hashtextextended(p_account_id::text,702)) then
            return jsonb_build_object('version',1,'retry',true);
        end if;
        snapshot := public.membership_fence(p_account_id,p_discord_user_id,false);
    end if;
    select exists(select 1 from public.membership_outbox
        where account_id=p_account_id and receipt_id is null) into pending;
    return jsonb_build_object('snapshot',snapshot,'pending',pending,
        'verificationPending',exists(select 1 from public.patreon_oauth_states
            where user_id=p_account_id
            and expected_generation=(snapshot->>'linkGeneration')::bigint
            and expires_at>clock_timestamp()));
end;
$function$;

revoke all on function public.membership_claim(uuid,integer),
    public.membership_ack_claim(uuid,uuid,uuid) from public,anon,authenticated;
grant execute on function public.membership_claim(uuid,integer),
    public.membership_ack_claim(uuid,uuid,uuid) to service_role;

commit;
