export const FEATURED_TAB = "featured";

export const featuredCommandNames: readonly string[] = [
    "coop.debug.players.list",
    "coop.debug.mobileparty.whoami",
    "coop.debug.hero.list",
    "coop.debug.town.list_towns",
    "coop.debug.village.list",
    "coop.debug.kingdom.list",
    "coop.debug.clan.list",
    "coop.debug.companions.list_wanderers",
    "coop.unstuck",
    "coop.debug.mapevent.leave_settlement",
    "coop.delete_player",
    "coop.debug.mobileparty.siege_buff",
    "coop.debug.clan.add_renown",
    "coop.debug.clan.add_influence",
    "coop.debug.hero.SetGold",
    "coop.debug.hero.set_relation",
    "coop.debug.herodeveloper.addskillxp",
    "coop.debug.herodeveloper.addattributepoints",
    "coop.debug.herodeveloper.addfocuspoints",
    "coop.debug.herodeveloper.resetskills",
    "coop.debug.crafting.givesupplies",
    "coop.debug.crafting.unlockallcraftingpieces",
    "coop.debug.kingdom.create",
    "coop.debug.kingdom.declare_war",
    "coop.debug.kingdom.make_peace",
    "coop.debug.settlements.set_ownerclan",
    "coop.debug.clan.remove_companion",
    "coop.debug.romance.start",
    "coop.debug.romance.compatible",
    "coop.debug.romance.agree",
    "coop.debug.romance.marry",
];

export function isFeaturedCommand(command: string) {
    return featuredCommandNames.includes(command);
}

export const featuredSummaries: Record<string, string> = {
    "coop.debug.players.list": "Lists players. The first entry should say (you). Most commands use the id after the first underscore.",
    "coop.debug.mobileparty.whoami": "Prints ids for your character so you can use them in other cheats.",
    "coop.debug.hero.list": "Lists hero ids. These ids are case-sensitive.",
    "coop.debug.town.list_towns": "Lists settlement ids for town and castle cheats.",
    "coop.debug.village.list": "Lists village ids.",
    "coop.debug.kingdom.list": "Lists kingdom ids for war, peace, and other kingdom cheats.",
    "coop.debug.clan.list": "Lists clans and their ids.",
    "coop.debug.companions.list_wanderers": "Lists wandering companions.",
    "coop.unstuck": "Asks the server to pull your party out of captivity, a settlement, or an army.",
    "coop.debug.mapevent.leave_settlement": "Try this if a character is stuck on Finishing Synchronization.",
    "coop.delete_player": "Deletes the current player's character so they can rejoin as a new one.",
    "coop.debug.mobileparty.siege_buff": "Adds about 2k troops and food, and prepares a party for a siege. Example: coop.debug.mobileparty.siege_buff Player",
    "coop.debug.clan.add_renown": "Adds renown to a clan.",
    "coop.debug.clan.add_influence": "Adds influence to a clan.",
    "coop.debug.hero.SetGold": "Sets a hero's gold.",
    "coop.debug.hero.set_relation": "Sets the relation between two heroes.",
    "coop.debug.herodeveloper.addskillxp": "Adds skill XP. Example: coop.debug.herodeveloper.addskillxp Bluey OneHanded 3000",
    "coop.debug.herodeveloper.addattributepoints": "Adds attribute points to a hero.",
    "coop.debug.herodeveloper.addfocuspoints": "Adds focus points to a hero.",
    "coop.debug.herodeveloper.resetskills": "Resets a hero's skills.",
    "coop.debug.crafting.givesupplies": "Gives a large amount of smithing supplies.",
    "coop.debug.crafting.unlockallcraftingpieces": "Unlocks every crafting piece.",
    "coop.debug.kingdom.create": "Creates a new kingdom. Use _ for spaces in the hero name.",
    "coop.debug.kingdom.declare_war": "Declares war between two factions.",
    "coop.debug.kingdom.make_peace": "Makes peace between two kingdoms.",
    "coop.debug.settlements.set_ownerclan": "Transfers settlement ownership. Example: coop.debug.settlements.set_ownerclan Danustica Player2865",
    "coop.debug.clan.remove_companion": "Removes a companion from a clan.",
    "coop.debug.romance.start": "Starts courtship. The NPC must not be in an army, a prisoner, or a battle.",
    "coop.debug.romance.compatible": "Marks the couple as compatible. The NPC must not be in an army, a prisoner, or a battle.",
    "coop.debug.romance.agree": "Marks the couple as agreed on marriage.",
    "coop.debug.romance.marry": "Finalizes the marriage.",
};
